package br.com.medflow.audit.domain;

/** Operações críticas rastreadas pelo backend. */
public enum AuditAction {
  ALTERAR_CLINICA,
  CRIAR_UNIDADE,
  ALTERAR_UNIDADE,
  CRIAR_CONSULTORIO,
  ALTERAR_CONSULTORIO,
  CRIAR_ESPECIALIDADE,
  ALTERAR_ESPECIALIDADE,
  CRIAR_MEDICO,
  ALTERAR_MEDICO,
  CRIAR_REGRA_AGENDA,
  ALTERAR_REGRA_AGENDA,
  CRIAR_BLOQUEIO_AGENDA,
  ALTERAR_BLOQUEIO_AGENDA,
  AGENDAR,
  REAGENDAR,
  CANCELAR,
  REALIZAR_CHECK_IN,
  INICIAR_ATENDIMENTO,
  SALVAR_REGISTRO_CLINICO,
  FINALIZAR_ATENDIMENTO,
  LER_REGISTRO_CLINICO,
  CONSULTAR_HISTORICO_CLINICO,
  CONSULTAR_AUDITORIA
}
