import { httpResource } from "@angular/common/http";
import { ChangeDetectionStrategy, Component, computed, inject, signal } from "@angular/core";
import { toSignal } from "@angular/core/rxjs-interop";
import { ActivatedRoute, Router, RouterLink } from "@angular/router";
import { HlmAlertImports } from "@spartan-ng/helm/alert";
import { HlmButtonImports } from "@spartan-ng/helm/button";
import { HlmCalendarImports } from "@spartan-ng/helm/calendar";
import { HlmCardImports } from "@spartan-ng/helm/card";
import { HlmSpinnerImports } from "@spartan-ng/helm/spinner";
import { finalize, map } from "rxjs";
import { IdentityService } from "../../auth/identity.service";
import { PageHeaderComponent } from "../../shared/ui/page-header.component";
import { StatePanelComponent } from "../../shared/ui/state-panel.component";
import { PatientApi, patientIssue } from "./patient.api";
import { Appointment, Availability, Slot } from "./patient.models";
@Component({ selector: "app-patient-reschedule", changeDetection: ChangeDetectionStrategy.OnPush, providers: [PatientApi], imports: [RouterLink, HlmAlertImports, HlmButtonImports, HlmCalendarImports, HlmCardImports, HlmSpinnerImports, PageHeaderComponent, StatePanelComponent], template: `<div class="flex flex-col gap-6"><app-page-header title="Reagendar consulta" description="O horário atual só será alterado depois da confirmação." />@if (appointment.isLoading()) { <app-state-panel state="loading" title="Carregando consulta" description="Aguarde um momento." /> } @else if (appointment.error() || !appointment.value()) { <app-state-panel state="error" [title]="issue(appointment.error()).title" [description]="issue(appointment.error()).description" /><a hlmBtn variant="outline" routerLink="/workspace/patient/consultas">Voltar</a> } @else { @let current = appointment.value()!;<section hlmCard><div hlmCardHeader><h1 hlmCardTitle>Horário atual</h1><p hlmCardDescription>{{ current.especialidade.nome }} · {{ dateTime(current.inicio) }} · {{ current.medico.nome }}</p></div><div hlmCardContent class="grid gap-6 lg:grid-cols-[20rem_1fr]"><section><h2 class="mb-3 font-semibold">Nova data</h2><hlm-calendar [date]="date()" [min]="today" (dateChange)="changeDate($event)" /></section><section class="flex flex-col gap-3"><h2 class="font-semibold">Novo horário</h2>@if (availability.isLoading()) { <app-state-panel state="loading" title="Buscando horários" description="Aguarde um momento." /> } @else if (availability.error()) { <app-state-panel state="error" [title]="issue(availability.error()).title" [description]="issue(availability.error()).description" /> } @else { <div class="grid gap-2 sm:grid-cols-2">@for (item of slots(); track item.regraAgendaId + item.inicio) { <button hlmBtn variant="outline" type="button" class="min-h-11 h-auto justify-start py-3 text-start" [attr.aria-pressed]="selected() === item" (click)="selected.set(item)">{{ time(item.inicio) }} · {{ item.consultorio.nome }}</button> }</div> }</section></div><div hlmCardFooter class="gap-3"><a hlmBtn variant="outline" routerLink="/workspace/patient/consultas">Voltar</a><button hlmBtn type="button" [disabled]="!selected() || saving()" (click)="confirm(current)">@if (saving()) { <hlm-spinner /> } Confirmar reagendamento</button></div></section>@if (problem(); as item) { <section hlmAlert><h2 hlmAlertTitle>{{ item.title }}</h2><p hlmAlertDescription>{{ item.description }}</p></section> } }</div>` })
export class PatientRescheduleComponent { private readonly api = inject(PatientApi); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly identity = inject(IdentityService); private readonly id = toSignal(this.route.paramMap.pipe(map((params) => params.get("id") ?? "")), { initialValue: "" }); readonly appointment = httpResource<Appointment>(() => this.id() ? this.api.appointment(this.id()) : undefined); protected readonly today = new Date(); protected readonly date = signal(new Date()); protected readonly selected = signal<Slot | null>(null); protected readonly saving = signal(false); protected readonly problem = signal<ReturnType<typeof patientIssue> | null>(null); protected readonly availability = httpResource<Availability>(() => this.id() ? this.api.rescheduleAvailability(this.id(), this.civilDate()) : undefined); protected readonly slots = computed(() => this.availability.value()?.items ?? []); protected changeDate(value: Date) { this.date.set(value); this.selected.set(null); } protected confirm(current: Appointment) { const item = this.selected(); if (!item) return; this.saving.set(true); this.api.reschedule(current.id, item.regraAgendaId, item.inicio, current.version).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => void this.router.navigateByUrl("/workspace/patient/consultas"), error: (error) => { const issue = patientIssue(error); this.problem.set(issue); if (issue.code === "HORARIO_INDISPONIVEL") { this.selected.set(null); this.availability.reload(); } if (issue.conflict) this.appointment.reload(); } }); } protected issue(error: unknown) { return patientIssue(error); } protected time(value: string) { return new Intl.DateTimeFormat("pt-BR", { timeStyle: "short", timeZone: this.identity.identity.value()?.timeZone }).format(new Date(value)); } protected dateTime(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeStyle: "short", timeZone: this.identity.identity.value()?.timeZone }).format(new Date(value)); } private civilDate() { const date = this.date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; } }
