import { httpResource } from "@angular/common/http";
import { ChangeDetectionStrategy, Component, computed, inject, signal } from "@angular/core";
import { toSignal } from "@angular/core/rxjs-interop";
import { ActivatedRoute, Router, RouterLink } from "@angular/router";
import { HlmAlertImports } from "@spartan-ng/helm/alert";
import { HlmButtonImports } from "@spartan-ng/helm/button";
import { HlmCalendarImports } from "@spartan-ng/helm/calendar";
import { HlmCardImports } from "@spartan-ng/helm/card";
import { HlmSpinnerImports } from "@spartan-ng/helm/spinner";
import { finalize, map } from "rxjs";
import { IdentityService } from "../../auth/identity.service";
import { PageHeaderComponent } from "../../shared/ui/page-header.component";
import { StatePanelComponent } from "../../shared/ui/state-panel.component";
import { PatientApi, patientIssue } from "./patient.api";
import { Appointment, Availability, Slot } from "./patient.models";

@Component({ selector: "app-patient-reschedule", changeDetection: ChangeDetectionStrategy.OnPush, providers: [PatientApi], imports: [RouterLink, HlmAlertImports, HlmButtonImports, HlmCalendarImports, HlmCardImports, HlmSpinnerImports, PageHeaderComponent, StatePanelComponent], template: `
  <div class="flex flex-col gap-6"><app-page-header title="Reagendar consulta" description="O horário atual só será alterado depois da confirmação." />
  @if (appointment.isLoading()) { <app-state-panel state="loading" title="Carregando consulta" description="Aguarde um momento." /> } @else if (appointment.error() || !appointment.value()) { <app-state-panel state="error" [title]="issue(appointment.error()).title" [description]="issue(appointment.error()).description" /><a hlmBtn variant="outline" routerLink="/workspace/patient/consultas">Voltar</a> } @else { @let current = appointment.value()!;
    <section hlmCard><div hlmCardHeader><h2 hlmCardTitle>Horário atual</h2><p hlmCardDescription>{{ current.especialidade.nome }} · {{ dateTime(current.inicio) }} · {{ current.medico.nome }}</p></div><div hlmCardContent class="grid gap-6 lg:grid-cols-[20rem_1fr]"><section><h2 class="mb-3 font-semibold">Nova data</h2><hlm-calendar [date]="date()" [min]="today" (dateChange)="changeDate($event)" /></section><section class="flex flex-col gap-3"><h2 class="font-semibold">Novo horário</h2>@if (availability.isLoading()) { <app-state-panel state="loading" title="Buscando horários" description="Aguarde um momento." /> } @else if (availability.error()) { <app-state-panel state="error" [title]="issue(availability.error()).title" [description]="issue(availability.error()).description" /> } @else { <div class="grid gap-2 sm:grid-cols-2">@for (item of slots(); track item.regraAgendaId + item.inicio) { <button hlmBtn [variant]="selected() === item ? 'default' : 'outline'" type="button" class="min-h-11 h-auto justify-start py-3 text-start" [attr.aria-pressed]="selected() === item" (click)="choose(item)"><span class="flex flex-col items-start"><span>{{ time(item.inicio) }} · {{ item.consultorio.nome }}</span>@if (selected() === item) { <span class="text-xs font-semibold">Selecionado</span> }</span></button> }</div> }</section></div><div hlmCardFooter class="gap-3"><a hlmBtn variant="outline" routerLink="/workspace/patient/consultas">Voltar</a><button hlmBtn type="button" [disabled]="!selected()" (click)="review.set(true)">Revisar novo horário</button></div></section>
    @if (review() && selected(); as next) { <section hlmCard><div hlmCardHeader><h2 hlmCardTitle>Revise a alteração</h2><p hlmCardDescription>O horário atual só muda depois da confirmação.</p></div><div hlmCardContent class="grid gap-4 md:grid-cols-2"><section class="border-border flex flex-col gap-3 rounded-md border p-4"><h3 class="font-semibold">Atual</h3><dl class="grid gap-2 text-sm"><div><dt class="text-muted-foreground">Data e horário</dt><dd class="font-medium">{{ dateTime(current.inicio) }}</dd></div><div><dt class="text-muted-foreground">Unidade</dt><dd class="font-medium">{{ current.unidade.nome }}</dd></div><div><dt class="text-muted-foreground">Consultório</dt><dd class="font-medium">{{ current.consultorio.nome }}</dd></div></dl></section><section class="border-primary flex flex-col gap-3 rounded-md border p-4"><h3 class="font-semibold">Novo</h3><dl class="grid gap-2 text-sm"><div><dt class="text-muted-foreground">Data e horário</dt><dd class="font-medium">{{ dateTime(next.inicio) }}</dd></div><div><dt class="text-muted-foreground">Unidade</dt><dd class="font-medium">{{ next.unidade.nome }}</dd></div><div><dt class="text-muted-foreground">Consultório</dt><dd class="font-medium">{{ next.consultorio.nome }}</dd></div></dl></section></div><div hlmCardFooter class="gap-3"><button hlmBtn variant="outline" type="button" (click)="review.set(false)">Voltar</button><button hlmBtn type="button" [disabled]="saving()" (click)="confirm(current, next)">@if (saving()) { <hlm-spinner /> } Confirmar reagendamento</button></div></section> }
    @if (problem(); as item) { <section hlmAlert><h2 hlmAlertTitle>{{ item.title }}</h2><p hlmAlertDescription>{{ item.description }}</p></section> }
  }</div>
` })
export class PatientRescheduleComponent {
  private readonly api = inject(PatientApi); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly identity = inject(IdentityService); private readonly id = toSignal(this.route.paramMap.pipe(map((params) => params.get("id") ?? "")), { initialValue: "" });
  readonly appointment = httpResource<Appointment>(() => this.id() ? this.api.appointment(this.id()) : undefined); protected readonly today = new Date(); protected readonly date = signal(new Date()); protected readonly selected = signal<Slot | null>(null); protected readonly review = signal(false); protected readonly saving = signal(false); protected readonly problem = signal<ReturnType<typeof patientIssue> | null>(null); protected readonly availability = httpResource<Availability>(() => this.id() ? this.api.rescheduleAvailability(this.id(), this.civilDate()) : undefined); protected readonly slots = computed(() => this.availability.value()?.items ?? []);
  protected choose(slot: Slot) { this.selected.set(slot); this.review.set(false); } protected changeDate(value: Date) { this.date.set(value); this.selected.set(null); this.review.set(false); }
  protected confirm(current: Appointment, item: Slot) { this.saving.set(true); this.api.reschedule(current.id, item.regraAgendaId, item.inicio, current.version).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => void this.router.navigateByUrl("/workspace/patient/consultas"), error: (error) => { const issue = patientIssue(error); this.problem.set(issue); if (issue.code === "HORARIO_INDISPONIVEL") { this.selected.set(null); this.review.set(false); this.availability.reload(); } if (issue.conflict) this.appointment.reload(); } }); }
  protected issue(error: unknown) { return patientIssue(error); } protected time(value: string) { return new Intl.DateTimeFormat("pt-BR", { timeStyle: "short", timeZone: this.identity.identity.value()?.timeZone }).format(new Date(value)); } protected dateTime(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeStyle: "short", timeZone: this.identity.identity.value()?.timeZone }).format(new Date(value)); } private civilDate() { const date = this.date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
}
